import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create New Post",
  description: "Generated by create next app",
};

export default function PostsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
